services:
  signal-bot:
    build: .
    env_file: .env
    network_mode: "host"
    environment:
      - SIGNAL_SERVICE=127.0.0.1:18380
      - SIGNAL_PHONE_NUMBER=${SIGNAL_PHONE_NUMBER}
      - PRIVATEMODE_BASE_URL=${PRIVATEMODE_BASE_URL}
      - PRIVATEMODE_MODEL=${PRIVATEMODE_MODEL}
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped

  privatemode-proxy:
    image: ghcr.io/edgelesssys/privatemode/privatemode-proxy:latest
    environment:
      - PRIVATEMODE_API_KEY=${PRIVATEMODE_API_KEY:-}
      - PRIVATEMODE_CACHE_MODE=${PRIVATEMODE_CACHE_MODE:-none}
      - PRIVATEMODE_CACHE_SALT=${PRIVATEMODE_CACHE_SALT:-}
    entrypoint: ["/bin/privatemode-proxy"]
    command: [
      "--apiKey=${PRIVATEMODE_API_KEY}",
      "--port=8080"
    ]
    ports:
      - "28082:8080"
    profiles: ["privatemode"]
    restart: unless-stopped


